name: Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

env:
  QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
  QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
  QSTASH_NEXT_SIGNING_KEY: ${{ secrets.QSTASH_NEXT_SIGNING_KEY }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Install Go tools
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build
        run: make

      - name: Test
        run: make test